# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

reportStatus: true

mergeMethod: squash
mergeCommitMessage: |
  {title} (#{number})
  {body}
deleteBranchAfterMerge: true

minApprovals:
  COLLABORATOR: 1
maxRequestedChanges:
  COLLABORATOR: 0

blockingTitleRegex: '/\bwip\b/i'
blockingLabels:
- WIP
- Dont merge
requiredLabels:
- Automerge
